AWSTemplateFormatVersion: 2010-09-09
Resources:
  S3Bucket:
    DeletionPolicy: Retain
    # above garantee not delete buket if we delete stack mashharawi
    Type: AWS::S3::Bucket
    Description: Create Amazon S3 bucket using CloudFormation
    Properties:
      BucketName: YOUR-BUCKET-NAME
      BucketEncryption: 
        ServerSideEncryptionConfiguration: 
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled
Outputs:
  S3Bucket:
    Description: S3 bucket created from a CloudFormation template
    Value: !Ref S3Bucket
